name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "SM-G960F_2_20200115133141_g3p4pxy3bj_fac"
  comment: "For those samsung s9 peeps"
  url: "https://upasset0109.b-cdn.net/GALAXYS9/SM-G960F/INS/SM-G960F_2_20200115133141_g3p4pxy3bj_fac.zip?token=ENfnY5Ppqp0a89x_p06s4w&expires=1613913167"
  file_name: "SM-G960F_2_20200115133141_g3p4pxy3bj_fac"
  piece_size: 22 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
